[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "lsd -l"

[[session]]
name = "Projects ğŸ“‚"
path = "~/projects"
startup_command = "lsd -l"

[[session]]
name = "Projects ğŸ“‚"
path = "~/projects"
startup_command = "lsd -l"

[[session]]
name = "Projects lua î˜  ğŸ“‚"
path = "~/projects/lua_Projects"
startup_command = "lsd -l"

[[session]]
name = "Projects rust î¨ ğŸ“‚"
path = "~/projects/rust_Projects"
startup_command = "lsd -l"

[[session]]
name = "Projects go î˜§ ğŸ“‚"
path = "~/projects/go_Projects"
startup_command = "lsd -l"

[[session]]
name = "Projects python î˜† ğŸ“‚"
path = "~/projects/python_Projects"
startup_command = "lsd -l"

[[session]]
name = "Projects cpp î˜ ğŸ“‚"
path = "~/projects/cpp_Projects"
startup_command = "lsd -l"

[[session]]
name = "Projects ocaml î™º ğŸ“‚"
path = "~/projects/ocaml_Projects"
startup_command = "lsd -l"

[[session]]
name = "Projects java îœ¸ ğŸ“‚"
path = "~/projects/java_Projects"
startup_command = "lsd -l"

[[session]]
name = "Projects js î˜Œ ğŸ“‚"
path = "~/projects/js_Projects"
startup_command = "lsd -l"

[[session]]
name = "Projects asm îš« ğŸ“‚" # ğŸ”§
path = "~/projects/asm_Projects"
startup_command = "lsd -l"

[[session]]
name = "Projects bend îŠ„ ğŸ“‚"
path = "~/projects/bend_Projects"
startup_command = "lsd -l"

[[session]]
name = "Projects C î˜ ğŸ“‚"
path = "~/projects/c_Projects"
startup_command = "lsd -l"

[[session]]
name = "Projects haskell î˜Ÿ ğŸ“‚"
path = "~/projects/haskell_Projects"
startup_command = "lsd -l"

[[session]]
name = "Projects elixir î˜­ ğŸ“‚"
path = "~/projects/elixir_Projects"
startup_command = "lsd -l"

[[session]]
name = "Projects latex îš› ğŸ“‚" #ï€‚
path = "~/projects/LaTex_Projects"
startup_command = "lsd -l"

[[session]]
name = "Dotfiles î˜• ğŸ“‚"
path = "~/dotfiles"
startup_command = "lsd -l"

[[session]]
name = "Casual âš’ï¸"
path = "~/"
startup_command = "lsd -l"
