[colors]
background = '#0f1414'
foreground = '#dee4e2'

cursor_bg = '#62d8d3'
cursor_fg = '#0f1414'
cursor_border = '#62d8d3'

selection_bg = '#3ebab5'
selection_fg = '#dee4e2'

ansi = ['#0f1414', '#e44a51', '#78d66e', '#dbca7b', '#20a099', '#5ba29e', '#62d8d3', '#abb2bf']
brights = ['#5c6370', '#e05f69', '#8ee086', '#e8d997', '#68e8e2', '#2e8772', '#418288', '#ffffff']
